@tool
extends Node3D

@export_multiline var sign_text : String:
	set(new_text):
		sign_text = new_text
		sign_label3d.text = sign_text
@export var show_pole : bool:
	set(new_val):
		show_pole = new_val
		pole.visible = show_pole


@export var sign_label3d : Label3D
@export var pole : Node3D


# Called when the node enters the scene tree for the first time.
func _ready():
	sign_label3d = $Label3D
	pole = $MeshInstance3D2
	pole.visible = show_pole
	sign_label3d.text = sign_text

	
	
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass
