@tool
extends Area3D

@export var size : Vector3 = Vector3(1,1,1):
	set(new_size):
		size = new_size
		mesh.mesh = mesh.mesh.duplicate()
		mesh.mesh.size = size
		collider.shape = collider.shape.duplicate()
		collider.shape.size = size

@export var mesh : MeshInstance3D
@export var collider : CollisionShape3D
var kill = true

# Called when the node enters the scene tree for the first time.
func _ready():
	mesh = $MeshInstance3D
	collider = $CollisionShape3D
	mesh.mesh = mesh.mesh.duplicate()
	mesh.mesh.size = size
	collider.shape = collider.shape.duplicate()
	collider.shape.size = size
	
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass
